# Generated by Django 4.2.6 on 2023-10-24 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_ID', models.CharField(max_length=50)),
                ('cont_first_name', models.CharField(max_length=200)),
                ('cont_last_name', models.CharField(max_length=200)),
                ('cont_preferredService', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_id', models.CharField(max_length=50)),
                ('rev_rating', models.CharField(max_length=5)),
                ('rev_comments', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_id', models.CharField(max_length=50)),
                ('serv_title', models.CharField(max_length=200)),
                ('serv_info', models.CharField(max_length=200)),
                ('serv_cost', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='LawnCare.review')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='serv_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='LawnCare.service'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inv_no', models.CharField(max_length=50)),
                ('Inv_date', models.CharField(max_length=200)),
                ('Inv_total', models.CharField(max_length=200)),
                ('Inv_description', models.CharField(max_length=200)),
                ('serv_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='LawnCare.service')),
            ],
        ),
    ]
