# Generated by Django 4.2.6 on 2023-10-24 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LawnCare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcontact',
            name='usr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
